sets.exported={
    main="Kaja Sword",
    sub={ name="Genbu's Shield", augments={'"Cure" potency +3%','Mag. Acc.+3',}},
    range="Gjallarhorn",
    head="Nyame Helm",
    body="Nyame Mail",
    hands="Nyame Gauntlets",
    legs="Nyame Flanchard",
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck="Sanctity Necklace",
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Digni. Earring",
    right_ear={ name="Fili Earring", augments={'System: 1 ID: 1676 Val: 0','Accuracy+6','Mag. Acc.+6',}},
    left_ring="Petrov Ring",
    right_ring="Apate Ring",
    back="Agema Cape",
}